// ─── Web3 AI Platform — Central Data Store ───────────────────────────────────

window.STORE = {

  // ─── Glossary Terms ───────────────────────────────────────────────────────
  glossary: [
    { term:"Airdrop", cat:"DeFi", def:"Free distribution of tokens to wallet addresses, usually as a marketing tool or community reward.", example:"Uniswap airdropped 400 UNI tokens to all early users in 2020.", related:["Token","Wallet","Smart Contract"] },
    { term:"AMM", cat:"DeFi", def:"Automated Market Maker — a decentralized exchange protocol that uses mathematical formulas to price assets instead of an order book.", example:"Uniswap V3 uses an AMM with concentrated liquidity.", related:["DEX","Liquidity Pool","Slippage"] },
    { term:"ABI", cat:"Infrastructure", def:"Application Binary Interface — a JSON specification describing how to interact with a smart contract's functions and events.", example:"You need the ABI to call functions on a deployed ERC-20 token.", related:["Smart Contract","Solidity","Ethers.js"] },
    { term:"Arbitrage", cat:"DeFi", def:"Exploiting price differences of the same asset across different exchanges to profit with minimal risk.", example:"Buy ETH on Exchange A for $2900 and sell on Exchange B for $2920.", related:["MEV","DEX","Liquidity"] },
    { term:"Account Abstraction", cat:"Infrastructure", def:"Allowing smart contracts to act as wallet accounts, enabling programmable gas payments and custom auth logic.", example:"ERC-4337 introduces account abstraction without protocol changes.", related:["ERC-4337","Gas","Wallet"] },
    { term:"Bitcoin", cat:"Infrastructure", def:"The first decentralized cryptocurrency, created in 2009 by Satoshi Nakamoto, operating on a proof-of-work blockchain.", example:"Bitcoin's max supply is 21 million BTC.", related:["Blockchain","PoW","Halving"] },
    { term:"Blockchain", cat:"Infrastructure", def:"A distributed, immutable ledger of transactions grouped into blocks, secured by cryptography and consensus mechanisms.", example:"Ethereum is a programmable blockchain that supports smart contracts.", related:["Block","Consensus","Hash"] },
    { term:"Block", cat:"Infrastructure", def:"A container of validated transactions added to the blockchain, identified by its hash and block number.", example:"Ethereum produces a new block roughly every 12 seconds.", related:["Blockchain","Miner","Transaction"] },
    { term:"Bridge", cat:"Infrastructure", def:"A protocol that allows tokens and data to move between different blockchains.", example:"Use the Arbitrum bridge to move ETH from Ethereum mainnet to Arbitrum.", related:["Layer 2","Cross-chain","Interoperability"] },
    { term:"Burn", cat:"DeFi", def:"Permanently removing tokens from circulation by sending them to an unspendable address, reducing supply.", example:"EIP-1559 burns a portion of ETH gas fees with every transaction.", related:["Supply","Deflationary","EIP-1559"] },
    { term:"Cold Wallet", cat:"Wallet", def:"A hardware or paper wallet that stores private keys offline, offering maximum security against hacking.", example:"Ledger Nano X and Trezor are popular cold wallets.", related:["Hot Wallet","Private Key","Seed Phrase"] },
    { term:"Consensus", cat:"Infrastructure", def:"A mechanism by which blockchain nodes agree on the valid state of the ledger.", example:"Bitcoin uses Proof of Work; Ethereum uses Proof of Stake.", related:["PoW","PoS","Validator"] },
    { term:"DAO", cat:"DAO", def:"Decentralized Autonomous Organization — a community governed by on-chain voting with no central authority.", example:"MakerDAO governs the DAI stablecoin through MKR token votes.", related:["Governance","Token","Vote"] },
    { term:"DApp", cat:"DeFi", def:"Decentralized Application — a frontend app that interacts with smart contracts on a blockchain.", example:"Aave is a DApp for lending and borrowing crypto.", related:["Smart Contract","Web3","Frontend"] },
    { term:"DeFi", cat:"DeFi", def:"Decentralized Finance — financial services built on blockchains with no need for banks or intermediaries.", example:"You can earn yield on Compound by lending USDC.", related:["AMM","Lending","Stablecoin"] },
    { term:"DEX", cat:"DeFi", def:"Decentralized Exchange — a platform for trading crypto assets directly from wallets with no central authority.", example:"Uniswap, Curve, Balancer are popular DEXes.", related:["AMM","CEX","Liquidity Pool"] },
    { term:"EIP", cat:"Infrastructure", def:"Ethereum Improvement Proposal — a design document for proposing changes to the Ethereum protocol.", example:"EIP-1559 changed Ethereum's fee market, adding a base fee burn.", related:["ERC","Governance","Hard Fork"] },
    { term:"ERC-20", cat:"DeFi", def:"A standard interface for fungible tokens on Ethereum, enabling interoperability across wallets and exchanges.", example:"USDC, LINK, and UNI are all ERC-20 tokens.", related:["ERC-721","Token","Smart Contract"] },
    { term:"ERC-721", cat:"NFT", def:"A standard for non-fungible tokens (NFTs) on Ethereum where each token has a unique ID and owner.", example:"CryptoPunks and BAYC are ERC-721 NFT collections.", related:["ERC-20","NFT","Metadata"] },
    { term:"ERC-1155", cat:"NFT", def:"A multi-token standard allowing both fungible and non-fungible tokens in a single contract.", example:"Game items using ERC-1155 can have quantities (swords: 500) and unique pieces.", related:["ERC-721","NFT","Gaming"] },
    { term:"Ethereum", cat:"Infrastructure", def:"A programmable blockchain platform supporting smart contracts and DApps, with ETH as its native currency.", example:"Most DeFi and NFT projects are built on Ethereum.", related:["Solidity","Gas","Smart Contract"] },
    { term:"EVM", cat:"Infrastructure", def:"Ethereum Virtual Machine — the sandboxed runtime environment that executes smart contract bytecode.", example:"Polygon, BSC, and Avalanche are EVM-compatible chains.", related:["Bytecode","Solidity","Smart Contract"] },
    { term:"Flash Loan", cat:"DeFi", def:"An uncollateralized loan that must be borrowed and repaid within the same transaction block.", example:"Aave offers flash loans for arbitrage and liquidations.", related:["Arbitrage","Liquidity","DeFi"] },
    { term:"Fork", cat:"Infrastructure", def:"A change in a blockchain's protocol. A hard fork is incompatible; a soft fork is backward-compatible.", example:"Ethereum Classic resulted from the hard fork after The DAO hack in 2016.", related:["Hard Fork","Soft Fork","Governance"] },
    { term:"FUD", cat:"Infrastructure", def:"Fear, Uncertainty, and Doubt — often spread to manipulate crypto markets downward.", example:"Negative news about crypto regulation often causes FUD-driven sell-offs.", related:["FOMO","Market","Sentiment"] },
    { term:"Gas", cat:"Infrastructure", def:"A unit measuring the computational work required to execute operations on the Ethereum network.", example:"A simple ETH transfer costs 21,000 gas units.", related:["Gas Price","Gwei","EIP-1559"] },
    { term:"Gas Price", cat:"Infrastructure", def:"The amount of ETH paid per unit of gas, denominated in Gwei, for transaction priority.", example:"During network congestion, gas prices spike above 100 Gwei.", related:["Gas","Gwei","Transaction"] },
    { term:"Governance", cat:"DAO", def:"The process by which protocol changes are proposed, voted on, and implemented by token holders.", example:"Compound token holders vote on protocol parameters via on-chain governance.", related:["DAO","Token","Vote"] },
    { term:"Gwei", cat:"Infrastructure", def:"A denomination of ETH (1 ETH = 1 billion Gwei) used to express gas prices.", example:"A gas price of 30 Gwei is relatively low on Ethereum mainnet.", related:["Gas","ETH","Wei"] },
    { term:"Halving", cat:"Infrastructure", def:"A Bitcoin event that cuts the block reward in half approximately every 4 years, reducing new supply.", example:"Bitcoin's 2024 halving reduced the block reward from 6.25 to 3.125 BTC.", related:["Bitcoin","Mining","Supply"] },
    { term:"Hash", cat:"Infrastructure", def:"A fixed-length cryptographic fingerprint of data produced by a hash function (e.g., SHA-256, Keccak).", example:"Each Ethereum transaction is identified by a unique 32-byte hash.", related:["Blockchain","Cryptography","Block"] },
    { term:"Hot Wallet", cat:"Wallet", def:"A software wallet connected to the internet, convenient for frequent transactions but more vulnerable to attacks.", example:"MetaMask is a popular hot wallet browser extension.", related:["Cold Wallet","Private Key","MetaMask"] },
    { term:"Impermanent Loss", cat:"DeFi", def:"The temporary loss of value experienced by liquidity providers when token ratios in a pool change.", example:"Providing ETH/USDC liquidity during high price volatility can cause impermanent loss.", related:["Liquidity Pool","AMM","Yield Farming"] },
    { term:"Layer 1", cat:"Layer 2", def:"The base blockchain layer responsible for consensus, security, and finality (e.g., Ethereum, Bitcoin).", example:"Ethereum is a Layer 1 that settles Layer 2 transactions.", related:["Layer 2","Blockchain","Consensus"] },
    { term:"Layer 2", cat:"Layer 2", def:"A scaling solution built on top of a Layer 1 blockchain to increase throughput and reduce fees.", example:"Arbitrum and Optimism are Ethereum Layer 2 rollups.", related:["Rollup","Layer 1","Bridge"] },
    { term:"Liquidity Pool", cat:"DeFi", def:"A smart contract holding reserves of token pairs used to facilitate decentralized trading.", example:"Add ETH and USDC to a Uniswap pool to earn trading fees.", related:["AMM","LP Token","Impermanent Loss"] },
    { term:"LP Token", cat:"DeFi", def:"A token representing a liquidity provider's share in a liquidity pool, redeemable for the underlying assets.", example:"When you provide liquidity to Uniswap, you receive LP tokens.", related:["Liquidity Pool","DeFi","Yield Farming"] },
    { term:"Mainnet", cat:"Infrastructure", def:"The live, production blockchain network where real transactions with real value occur.", example:"Deploy on Ethereum mainnet only after thorough testnet testing.", related:["Testnet","Network","Deploy"] },
    { term:"MEV", cat:"DeFi", def:"Maximal Extractable Value — profits miners/validators capture by reordering or inserting transactions.", example:"Frontrunning a large DEX trade is a common MEV strategy.", related:["Arbitrage","Flashbots","Gas"] },
    { term:"MetaMask", cat:"Wallet", def:"A popular browser extension and mobile wallet for interacting with Ethereum-based DApps.", example:"Connect MetaMask to Uniswap to swap tokens directly.", related:["Hot Wallet","Wallet","WalletConnect"] },
    { term:"Minting", cat:"NFT", def:"The process of creating and recording a new NFT or token on a blockchain.", example:"Artists mint NFTs on OpenSea or directly via smart contracts.", related:["NFT","Smart Contract","ERC-721"] },
    { term:"Multisig", cat:"Wallet", def:"A wallet requiring multiple private key signatures to authorize a transaction, improving security.", example:"Gnosis Safe is a popular multisig wallet for DAOs.", related:["Wallet","DAO","Security"] },
    { term:"NFT", cat:"NFT", def:"Non-Fungible Token — a unique, indivisible digital asset verified on a blockchain.", example:"Bored Ape Yacht Club NFTs grant membership and commercial rights to holders.", related:["ERC-721","Minting","Metadata"] },
    { term:"Node", cat:"Infrastructure", def:"A computer participating in a blockchain network by storing and validating the chain's data.", example:"Run a full Ethereum node with Geth or Erigon.", related:["Validator","Blockchain","Network"] },
    { term:"Nonce", cat:"Infrastructure", def:"A number that can only be used once — in Ethereum, it counts the number of transactions from an address.", example:"If your nonce is out of order, your transaction will get stuck pending.", related:["Transaction","Wallet","Gas"] },
    { term:"OpenSea", cat:"NFT", def:"The largest NFT marketplace for buying, selling, and minting digital collectibles and artwork.", example:"Browse over 2 million NFT collections on OpenSea.", related:["NFT","Minting","Marketplace"] },
    { term:"Oracle", cat:"Infrastructure", def:"A service that provides smart contracts with real-world off-chain data like prices, weather, or randomness.", example:"Chainlink is the most widely used decentralized oracle network.", related:["Chainlink","Smart Contract","Data Feed"] },
    { term:"Optimistic Rollup", cat:"Layer 2", def:"A Layer 2 scaling solution that assumes transactions are valid by default, with a fraud-proof window.", example:"Optimism and Arbitrum are optimistic rollup chains.", related:["Layer 2","ZK Rollup","Fraud Proof"] },
    { term:"Proof of Stake", cat:"Infrastructure", def:"A consensus mechanism where validators are chosen to create blocks based on their staked tokens.", example:"Ethereum moved to Proof of Stake in The Merge (2022).", related:["Validator","Staking","Consensus"] },
    { term:"Proof of Work", cat:"Infrastructure", def:"A consensus mechanism where miners compete to solve cryptographic puzzles to add blocks.", example:"Bitcoin uses Proof of Work with SHA-256 mining.", related:["Mining","Bitcoin","Consensus"] },
    { term:"Private Key", cat:"Wallet", def:"A secret 256-bit number giving complete control over a wallet's funds. Never share it.", example:"Your private key is like a master password — losing it means losing your funds.", related:["Public Key","Seed Phrase","Wallet"] },
    { term:"Public Key", cat:"Wallet", def:"A cryptographic key derived from the private key, used to generate your wallet address.", example:"Your Ethereum address is derived from your public key via Keccak-256.", related:["Private Key","Wallet","Address"] },
    { term:"Rollup", cat:"Layer 2", def:"A Layer 2 solution that bundles many transactions off-chain and posts compressed proofs to Layer 1.", example:"zkSync and StarkNet post validity proofs; Arbitrum posts fraud proofs.", related:["ZK Rollup","Optimistic Rollup","Layer 2"] },
    { term:"Rugpull", cat:"DeFi", def:"A scam where developers abandon a project and steal investor funds, typically by draining liquidity.", example:"Many low-cap DeFi tokens have been rugpulled within hours of launch.", related:["Scam","Liquidity","DeFi"] },
    { term:"Seed Phrase", cat:"Wallet", def:"A 12- or 24-word mnemonic that backs up all private keys in a hierarchical deterministic wallet.", example:"Write your seed phrase offline and store it securely — never share it.", related:["Private Key","Wallet","BIP-39"] },
    { term:"Slippage", cat:"DeFi", def:"The difference between the expected and actual trade price due to market movement or low liquidity.", example:"Set slippage tolerance to 0.5% on Uniswap to avoid failed swaps.", related:["AMM","Liquidity Pool","DEX"] },
    { term:"Smart Contract", cat:"Infrastructure", def:"Self-executing code stored on a blockchain that automatically enforces agreed-upon rules.", example:"A smart contract automatically releases escrow funds when delivery is confirmed.", related:["Solidity","EVM","DApp"] },
    { term:"Solidity", cat:"Infrastructure", def:"The primary object-oriented programming language for writing Ethereum smart contracts.", example:"Write and deploy an ERC-20 token in Solidity in under 50 lines of code.", related:["Smart Contract","EVM","ABI"] },
    { term:"Staking", cat:"Infrastructure", def:"Locking tokens in a protocol to earn rewards, secure the network, or gain governance rights.", example:"Stake 32 ETH to become a solo Ethereum validator.", related:["Proof of Stake","Validator","Yield"] },
    { term:"Stablecoin", cat:"DeFi", def:"A token pegged to a stable asset (usually USD) to minimize price volatility.", example:"USDC, USDT, and DAI are the most widely used stablecoins.", related:["DeFi","Peg","Collateral"] },
    { term:"Testnet", cat:"Infrastructure", def:"A test blockchain environment with no real value, used for development and testing.", example:"Deploy your contract on Goerli or Sepolia testnet before mainnet.", related:["Mainnet","Deploy","Faucet"] },
    { term:"Token", cat:"DeFi", def:"A digital asset created on a blockchain, representing value, access, or governance rights.", example:"ERC-20 tokens can represent anything from stablecoins to governance votes.", related:["ERC-20","Cryptocurrency","Wallet"] },
    { term:"Transaction", cat:"Infrastructure", def:"A signed instruction from a wallet that changes state on the blockchain (transfer, contract call, etc.).", example:"Swapping ETH on Uniswap creates an on-chain transaction.", related:["Gas","Nonce","Block"] },
    { term:"TVL", cat:"DeFi", def:"Total Value Locked — the total USD value of assets deposited in a DeFi protocol.", example:"Lido's TVL exceeded $30B, making it the largest liquid staking protocol.", related:["DeFi","Liquidity","Staking"] },
    { term:"Validator", cat:"Infrastructure", def:"A node that participates in blockchain consensus by proposing and attesting to blocks.", example:"Ethereum has over 900,000 active validators post-Merge.", related:["Staking","PoS","Node"] },
    { term:"Wallet", cat:"Wallet", def:"Software or hardware that stores private keys and allows users to interact with blockchains.", example:"MetaMask, Phantom, and Rainbow are popular Web3 wallets.", related:["Private Key","Public Key","Seed Phrase"] },
    { term:"WalletConnect", cat:"Wallet", def:"An open protocol for connecting DApps to mobile wallets via QR code or deep link.", example:"Scan a WalletConnect QR code on Uniswap to use your mobile wallet.", related:["MetaMask","DApp","Wallet"] },
    { term:"Web3", cat:"Infrastructure", def:"The vision of a decentralized internet built on blockchains, giving users ownership of their data and assets.", example:"Web3 apps let users log in with wallets instead of email/password.", related:["DApp","Blockchain","Decentralization"] },
    { term:"Whitepaper", cat:"Infrastructure", def:"A technical document outlining a blockchain project's goals, technology, tokenomics, and roadmap.", example:"Satoshi Nakamoto published the Bitcoin whitepaper in October 2008.", related:["Tokenomics","Roadmap","Project"] },
    { term:"Yield Farming", cat:"DeFi", def:"Deploying assets across DeFi protocols to maximize returns through fees, interest, and incentive tokens.", example:"Deposit USDC into Yearn Finance to auto-compound yield farming strategies.", related:["LP Token","Staking","DeFi"] },
    { term:"zk-SNARK", cat:"Layer 2", def:"Zero-Knowledge Succinct Non-Interactive Argument of Knowledge — a compact cryptographic proof used in ZK rollups.", example:"Zcash uses zk-SNARKs to verify private transactions.", related:["ZK Rollup","Privacy","Cryptography"] },
    { term:"ZK Rollup", cat:"Layer 2", def:"A Layer 2 scaling solution that posts cryptographic validity proofs to Layer 1 for instant finality.", example:"zkSync and StarkNet are major ZK rollup chains.", related:["Rollup","Optimistic Rollup","Layer 2"] },
    { term:"Zero Knowledge Proof", cat:"Layer 2", def:"A cryptographic method to prove knowledge of information without revealing it.", example:"Prove you're over 18 without revealing your exact birth date.", related:["zk-SNARK","Privacy","Layer 2"] },
    { term:"Chainlink", cat:"Infrastructure", def:"A decentralized oracle network providing real-world data to smart contracts on multiple blockchains.", example:"DeFi protocols use Chainlink price feeds to determine collateral ratios.", related:["Oracle","Data Feed","Smart Contract"] },
    { term:"Cross-chain", cat:"Infrastructure", def:"The ability for data, tokens, or messages to move between different blockchain networks.", example:"LayerZero enables cross-chain token transfers without wrapping.", related:["Bridge","Interoperability","Layer 1"] },
    { term:"Custody", cat:"Wallet", def:"Control over cryptographic keys. Self-custody means you hold your own keys; custodial means a third party holds them.", example:"Exchanges like Coinbase are custodial; MetaMask is self-custodial.", related:["Wallet","Private Key","Security"] },
    { term:"Decentralization", cat:"Infrastructure", def:"The distribution of control across many participants rather than a single central authority.", example:"Bitcoin is decentralized — no single entity can alter its rules.", related:["Blockchain","DAO","Governance"] },
    { term:"Ethers.js", cat:"Infrastructure", def:"A lightweight JavaScript library for interacting with the Ethereum blockchain and its ecosystem.", example:"Use ethers.js to query on-chain data and send transactions from a frontend.", related:["Web3.js","ABI","Smart Contract"] },
    { term:"IPFS", cat:"NFT", def:"InterPlanetary File System — a decentralized storage network for hosting files addressed by content hash.", example:"NFT metadata and images are often stored on IPFS to avoid centralized servers.", related:["NFT","Decentralization","Storage"] },
    { term:"Liquidity Mining", cat:"DeFi", def:"Earning protocol tokens as rewards for providing liquidity to a DeFi platform.", example:"Compound introduced liquidity mining by distributing COMP tokens to lenders.", related:["Yield Farming","Liquidity Pool","DeFi"] },
    { term:"Mempool", cat:"Infrastructure", def:"The memory pool of pending, unconfirmed transactions waiting to be included in a block.", example:"MEV bots monitor the mempool to frontrun profitable trades.", related:["Transaction","Gas","MEV"] },
    { term:"Miner", cat:"Infrastructure", def:"A node that validates transactions and produces new blocks using computational power (Proof of Work).", example:"Bitcoin miners earn block rewards and transaction fees.", related:["Mining","PoW","Block"] },
    { term:"On-chain", cat:"Infrastructure", def:"Data or computation that is recorded and executed directly on the blockchain.", example:"On-chain governance votes are final and transparent.", related:["Off-chain","Transaction","Smart Contract"] },
    { term:"Off-chain", cat:"Infrastructure", def:"Data or computation that happens outside the blockchain, often for speed or privacy.", example:"Layer 2 solutions process transactions off-chain and settle proofs on-chain.", related:["On-chain","Layer 2","Oracle"] },
    { term:"Phantom", cat:"Wallet", def:"A popular Solana wallet for storing SOL, SPL tokens, and Solana NFTs.", example:"Connect Phantom to Magic Eden to buy Solana NFTs.", related:["Wallet","Solana","NFT"] },
    { term:"Solana", cat:"Infrastructure", def:"A high-performance Layer 1 blockchain known for fast, low-cost transactions using Proof of History.", example:"Solana processes over 65,000 transactions per second.", related:["Layer 1","PoH","NFT"] },
    { term:"Tokenomics", cat:"DeFi", def:"The economic model of a cryptocurrency project, covering supply, distribution, utility, and incentives.", example:"Good tokenomics ensure long-term alignment between founders, investors, and users.", related:["Token","Supply","DAO"] },
    { term:"Vesting", cat:"DeFi", def:"A schedule that locks tokens and releases them gradually over time to align long-term incentives.", example:"Team tokens often vest over 4 years with a 1-year cliff.", related:["Tokenomics","DAO","Smart Contract"] },
    { term:"Whale", cat:"DeFi", def:"A large holder of cryptocurrency whose trades can significantly impact market prices.", example:"A whale sold 50,000 ETH causing a 5% market drop.", related:["Market","DeFi","Token"] },
  ],

  // ─── Job Listings ─────────────────────────────────────────────────────────
  jobs: [
    { id:1,  title:"Senior Solidity Developer",        company:"Uniswap Labs",      location:"Remote",         type:"Full-time", stack:["Solidity","Hardhat","TypeScript"], salary:"$150k–$220k", tags:["DeFi","Protocol"], logo:"🦄", posted:"2d ago" },
    { id:2,  title:"Frontend Web3 Engineer",           company:"OpenSea",           location:"Remote",         type:"Full-time", stack:["React","Ethers.js","Next.js"],     salary:"$120k–$180k", tags:["NFT","Frontend"],  logo:"🌊", posted:"3d ago" },
    { id:3,  title:"Rust Blockchain Developer",        company:"Solana Foundation", location:"Remote",         type:"Full-time", stack:["Rust","Anchor","TypeScript"],       salary:"$160k–$250k", tags:["Solana","Core"],   logo:"◎",  posted:"1d ago" },
    { id:4,  title:"Smart Contract Auditor",           company:"Trail of Bits",     location:"Remote",         type:"Full-time", stack:["Solidity","Python","Slither"],      salary:"$180k–$280k", tags:["Security","Audit"],logo:"🔐", posted:"5d ago" },
    { id:5,  title:"DeFi Protocol Engineer",           company:"Aave",              location:"Remote",         type:"Full-time", stack:["Solidity","TypeScript","GraphQL"],  salary:"$140k–$200k", tags:["DeFi","Protocol"], logo:"👻", posted:"1w ago" },
    { id:6,  title:"ZK Cryptographer",                 company:"StarkWare",         location:"Remote",         type:"Full-time", stack:["Cairo","Rust","Math"],              salary:"$200k–$350k", tags:["ZK","Research"],   logo:"⚡", posted:"3d ago" },
    { id:7,  title:"Web3 Product Manager",             company:"Coinbase",          location:"San Francisco",  type:"Full-time", stack:["Product","Analytics","SQL"],        salary:"$160k–$230k", tags:["Product","PM"],    logo:"🔵", posted:"4d ago" },
    { id:8,  title:"Blockchain DevRel Engineer",       company:"Chainlink",         location:"Remote",         type:"Full-time", stack:["Solidity","Node.js","Python"],      salary:"$110k–$160k", tags:["DevRel","Oracle"], logo:"🔗", posted:"2d ago" },
    { id:9,  title:"DAO Operations Lead",              company:"MakerDAO",          location:"Remote",         type:"Full-time", stack:["Governance","Excel","Python"],      salary:"$90k–$140k",  tags:["DAO","Ops"],       logo:"🏛️", posted:"6d ago" },
    { id:10, title:"NFT Smart Contract Dev",           company:"Art Blocks",        company:"Art Blocks",      location:"Remote",         type:"Contract", stack:["Solidity","JavaScript","IPFS"],   salary:"$100–$180/hr",tags:["NFT","Art"],     logo:"🎨", posted:"1d ago" },
    { id:11, title:"Layer 2 Protocol Engineer",        company:"Arbitrum",          location:"Remote",         type:"Full-time", stack:["Go","Rust","TypeScript"],           salary:"$180k–$260k", tags:["Layer 2","Core"],  logo:"🔷", posted:"1w ago" },
    { id:12, title:"Crypto Quantitative Analyst",      company:"Two Sigma",         location:"New York",       type:"Full-time", stack:["Python","R","C++"],                 salary:"$200k–$400k", tags:["Quant","Finance"], logo:"📊", posted:"2w ago" },
    { id:13, title:"Web3 Security Researcher",         company:"Immunefi",          location:"Remote",         type:"Full-time", stack:["Solidity","Python","EVM"],          salary:"$140k–$220k", tags:["Security","Bug Bounty"],logo:"🐛",posted:"3d ago" },
    { id:14, title:"Cross-chain Protocol Dev",         company:"LayerZero",         location:"Remote",         type:"Full-time", stack:["Solidity","TypeScript","Go"],       salary:"$160k–$240k", tags:["Cross-chain","Protocol"],logo:"∞",posted:"1d ago" },
    { id:15, title:"Technical Writer — Web3",          company:"Ethereum Foundation",location:"Remote",       type:"Part-time", stack:["Markdown","Solidity","Docs"],       salary:"$60k–$90k",   tags:["Writing","Docs"],  logo:"🖊️", posted:"5d ago" },
    { id:16, title:"Community Manager",                company:"Polkadot",          location:"Remote",         type:"Full-time", stack:["Discord","Twitter","Notion"],       salary:"$70k–$110k",  tags:["Community","DAO"], logo:"💜", posted:"4d ago" },
    { id:17, title:"Solana Program Developer",         company:"Magic Eden",        location:"Remote",         type:"Full-time", stack:["Rust","Anchor","TypeScript"],       salary:"$130k–$200k", tags:["Solana","NFT"],    logo:"🪄", posted:"3d ago" },
    { id:18, title:"MEV Researcher",                   company:"Flashbots",         location:"Remote",         type:"Full-time", stack:["Python","Go","Solidity"],           salary:"$180k–$300k", tags:["MEV","Research"],  logo:"🤖", posted:"1w ago" },
    { id:19, title:"Tokenomics Designer",              company:"Binance Labs",      location:"Remote",         type:"Contract", stack:["Economics","Python","Research"],    salary:"$120–$200/hr",tags:["Tokenomics","DAO"],logo:"🟡", posted:"6d ago" },
    { id:20, title:"Smart Contract Developer",         company:"Compound Finance",  location:"Remote",         type:"Full-time", stack:["Solidity","TypeScript","React"],    salary:"$130k–$190k", tags:["DeFi","Protocol"], logo:"🏦", posted:"2w ago" },
    { id:21, title:"Cairo Developer",                  company:"StarkNet",          location:"Remote",         type:"Full-time", stack:["Cairo","Python","Rust"],            salary:"$170k–$260k", tags:["ZK","Layer 2"],    logo:"🌟", posted:"4d ago" },
    { id:22, title:"Substrate Developer",              company:"Parity Technologies",location:"Remote",        type:"Full-time", stack:["Rust","Substrate","Go"],            salary:"$150k–$230k", tags:["Polkadot","Core"], logo:"⚙️", posted:"1w ago" },
    { id:23, title:"Web3 Growth Marketer",             company:"Polygon",           location:"Remote",         type:"Full-time", stack:["Marketing","Analytics","Web3"],     salary:"$80k–$130k",  tags:["Marketing","Growth"],logo:"🟣",posted:"3d ago" },
    { id:24, title:"DeFi Risk Analyst",                company:"Gauntlet",          location:"Remote",         type:"Full-time", stack:["Python","Statistics","Solidity"],   salary:"$130k–$200k", tags:["DeFi","Risk"],     logo:"🎯", posted:"5d ago" },
    { id:25, title:"Frontend Engineer — DeFi",         company:"dYdX",              location:"Remote",         type:"Full-time", stack:["React","TypeScript","GraphQL"],     salary:"$140k–$200k", tags:["DeFi","Frontend"], logo:"📈", posted:"2d ago" },
    { id:26, title:"Zero Knowledge Engineer",          company:"Aztec Network",     location:"Remote",         type:"Full-time", stack:["Rust","C++","Cryptography"],        salary:"$200k–$350k", tags:["ZK","Privacy"],    logo:"🔮", posted:"1d ago" },
    { id:27, title:"Blockchain Infrastructure Eng",    company:"Infura",            location:"Remote",         type:"Full-time", stack:["Go","Kubernetes","AWS"],            salary:"$140k–$200k", tags:["Infrastructure"],  logo:"🏗️", posted:"4d ago" },
    { id:28, title:"Crypto Compliance Officer",        company:"Kraken",            location:"San Francisco",  type:"Full-time", stack:["Legal","Compliance","KYC"],         salary:"$120k–$180k", tags:["Legal","Compliance"],logo:"⚖️",posted:"1w ago" },
    { id:29, title:"Protocol Researcher",              company:"Paradigm",          location:"Remote",         type:"Full-time", stack:["Research","Math","Solidity"],       salary:"$200k–$400k", tags:["Research","DeFi"], logo:"🔭", posted:"2w ago" },
    { id:30, title:"iOS Web3 Developer",               company:"Rainbow Wallet",    location:"Remote",         type:"Full-time", stack:["Swift","React Native","Ethers.js"], salary:"$130k–$190k", tags:["Mobile","Wallet"], logo:"🌈", posted:"3d ago" },
  ],

  // ─── AI Research Knowledge Base ───────────────────────────────────────────
  knowledge: {
    defi: {
      title: "Decentralized Finance (DeFi)",
      summary: "DeFi revolutionizes traditional finance by using smart contracts on blockchains to offer lending, borrowing, trading, and yield generation without intermediaries.",
      keyPoints: ["No banks or intermediaries needed","Transparent, auditable code","Permissionless access globally","Composable — protocols interact with each other","Risks: smart contract bugs, liquidation, impermanent loss"],
      protocols: ["Uniswap (DEX)", "Aave (Lending)", "Compound (Lending)", "Curve (Stablecoin AMM)", "MakerDAO (Stablecoin)", "Yearn Finance (Yield Aggregator)"],
      tvl: "$80B+",
      chains: ["Ethereum", "BNB Chain", "Polygon", "Arbitrum", "Optimism", "Solana"]
    },
    nft: {
      title: "Non-Fungible Tokens (NFTs)",
      summary: "NFTs are unique digital assets recorded on a blockchain, proving ownership of digital or physical items including art, music, gaming items, and real estate.",
      keyPoints: ["Each NFT has a unique token ID","Stored on-chain; metadata often on IPFS","ERC-721 standard on Ethereum","Royalties can be programmed into contracts","Use cases: art, gaming, music, tickets, identity"],
      protocols: ["OpenSea", "Blur", "Magic Eden (Solana)", "Rarible", "Foundation", "LooksRare"],
      standards: ["ERC-721", "ERC-1155", "Metaplex (Solana)", "ERC-6551 (Token Bound Accounts)"],
      chains: ["Ethereum", "Solana", "Polygon", "Tezos", "Flow", "Immutable X"]
    },
    layer2: {
      title: "Layer 2 Scaling Solutions",
      summary: "Layer 2 solutions increase blockchain throughput by processing transactions off-chain while inheriting security from the underlying Layer 1 network.",
      keyPoints: ["Dramatically lower fees (100x cheaper than L1)","Faster transaction finality","Rollups are the dominant L2 technology","Optimistic rollups: 7-day fraud-proof window","ZK rollups: instant finality via cryptographic proofs"],
      solutions: {
        optimistic: ["Arbitrum One","Optimism","Base","Blast"],
        zk: ["zkSync Era","StarkNet","Polygon zkEVM","Scroll","Linea"]
      },
      chains: ["Ethereum (L1)", "Arbitrum (L2)", "Optimism (L2)", "zkSync (L2)", "StarkNet (L2)"]
    },
    dao: {
      title: "Decentralized Autonomous Organizations (DAOs)",
      summary: "DAOs are internet-native organizations governed by token holders via on-chain voting, with no central leadership making unilateral decisions.",
      keyPoints: ["Governed by smart contracts","Token-based voting power","Proposals, discussion, then on-chain vote","Treasury managed by the DAO collectively","Challenges: voter apathy, plutocracy, legal status"],
      examples: ["MakerDAO","Uniswap DAO","Compound DAO","Gitcoin","Friends With Benefits","Constitution DAO"],
      tools: ["Snapshot (off-chain voting)","Tally (on-chain governance)","Gnosis Safe (treasury)","Discourse (forum)"]
    },
    wallet: {
      title: "Web3 Wallets & Security",
      summary: "Wallets are the gateway to Web3, storing private keys and enabling interaction with blockchains. Security best practices are critical to protecting your assets.",
      keyPoints: ["Never share your seed phrase","Hardware wallets offer the best security","Use separate wallets for different activities","Verify contract addresses before signing","Revoke unused token approvals regularly"],
      types: ["Hot Wallet (MetaMask, Rainbow)","Cold Wallet (Ledger, Trezor)","Smart Contract Wallet (Gnosis Safe)","Mobile Wallet (Coinbase Wallet, Trust Wallet)"],
      tools: ["Revoke.cash — revoke token approvals","Etherscan — verify contracts","DeBank — portfolio tracker","Nansen — on-chain analytics"]
    },
    blockchain: {
      title: "Blockchain Fundamentals",
      summary: "A blockchain is a distributed ledger of immutable transactions, secured by cryptography and maintained by a decentralized network of nodes.",
      keyPoints: ["Immutable — data cannot be altered once recorded","Transparent — all transactions publicly verifiable","Decentralized — no single point of failure","Consensus mechanisms ensure agreement","Hash functions link blocks cryptographically"],
      types: ["Public (Ethereum, Bitcoin)","Private (Hyperledger)","Consortium (R3 Corda)","Hybrid"],
      chains: ["Bitcoin","Ethereum","Solana","BNB Chain","Cardano","Avalanche","Polkadot"]
    }
  }
};
